#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

new_repo() {
  local path="$1"
  mkdir -p "$path"
  git -C "$path" init -q
  git -C "$path" config user.name test
  git -C "$path" config user.email test@example.com
  printf '# fixture\n' > "$path/README.md"
  git -C "$path" add README.md
  git -C "$path" commit -qm initial
}

tdd="$TMP/tdd"
new_repo "$tdd"
printf 'print("production")\n' > "$tdd/app.py"
if (cd "$tdd" && python3 "$ROOT/runtime/quality_gate.py"); then
  echo "TDD gate accepted a source-only change" >&2
  exit 1
fi

attribution="$TMP/attribution"
new_repo "$attribution"
printf 'This was generated by AI.\n' > "$attribution/notes.md"
if (cd "$attribution" && python3 "$ROOT/runtime/quality_gate.py"); then
  echo "attribution gate accepted prohibited text" >&2
  exit 1
fi

passing="$TMP/passing"
new_repo "$passing"
mkdir -p "$passing/tests"
printf 'def value(): return 1\n' > "$passing/app.py"
printf 'from app import value\n\ndef test_value(): assert value() == 1\n' > "$passing/tests/test_app.py"
(cd "$passing" && python3 "$ROOT/runtime/quality_gate.py")

echo "quality gate tests passed"
